feat: wrap subscription updates in a micro task to avoid state updates during render
Errors like this one:

Error: Cannot update a component (`Palette`) while rendering a different
component (`ClaimerPanel`). To locate the bad setState() call inside
`ClaimerPanel`